language: rust
os:
        - linux
        - osx
        - windows
script:
        - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cargo build --no-default-features --features "metal"; fi
        - if [ "$TRAVIS_OS_NAME" != "osx" ]; then cargo build --no-default-features --features "vulkan"; fi
rust:
        - stable
        - beta
        - nightly
jobs:
        allow_failures:
                - rust: nightly
        fast_finish: true
cache: cargo
addons:
        apt:
                packages: xorg-dev libglu1-mesa-dev pkg-config libasound2-dev
